Description:  This is an example of an AWS Cloudformation template in yaml format which deploys a VPC

Parameters:
  Prefix:
    Description: A prefix identifier for the VPC
    Type: String
    Default: iac-lab-cfn-yaml

  Environment:
    Description: An environment name, e.g. dev, test, uat
    Type: String
    Default: dev

  VpcCIDR:
    Description: An IP range (CIDR notation) for the VPC
    Type: String
    Default: 10.192.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref Prefix
              - '-example'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC